# Generated by Django 6.0.6 on 2026-06-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='I currently work here'),
        ),
    ]
